bcgov/jag-pcss-civil

src/pom.xml
- updating version of master pom file
N/A
=> update version on master pom

.github/workflows/maven-test-pr.yml
- Adding github action to run build
N/A
=> Adding git action to build the code

src/pcss-web-service/pom.xml
- Rename app name to match the artifactId
=> Renamed application

src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/WebServiceConfig.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/PcssCivilEndpoint.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilPartyMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/PartyMapper.java
- Adding logs to the endpoint
- Added mapping
locally with unit tests
=> Adding endpoint implementation

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
- Adding new endpoint on the swagger.
Locally
=> adding search-file appearance endpoint

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
Ran the yaml parsing via maven
=> New Endpoints

src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/PcssCivilEndpoint.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilPartyMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilResponseMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/ApprDetailMapper.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilPartyTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilTest.java
- implementing getAppearanceCivil 
Running the app locally
=> implementing getAppearanceCivil operation

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
PCSS Civil File Content Hearing REstrictions GET swagger info
=> New Endpoint

src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/Keys.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/PcssCivilEndpoint.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilApprMethodResponseMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilResponseMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceMethodMapper.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilApprMethodTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/TestHelpers.java
- implementing getAppearanceCivilApprMethod endpoint
=> implementing getAppearanceCivilApprMethod endpoint

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
civil sync appr get endpoint to swagger
=> Adding endpoint

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
Updated the swagger file to add GET civil/file-content ORDS endpoint
=> civil-file-content-get

src/libs/ords-pcss-client/ords.pcss.swagger.yaml, src/libs/ords-pcss-client/pom.xml, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/AutoConfiguration.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/Keys.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilService.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilServiceImpl.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/mappers/AppearanceDocumentResponseMapper.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/mappers/SearchFileAppearanceIssueResponseMapper.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/models/AppearanceDocumentData.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/models/AppearanceDocumentResponse.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/models/ResponseBase.java, src/libs/ords-pcss-client/src/test/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilServiceGetCivilSearchFileAppearanceDocumentTest.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/WebServiceConfig.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/PcssCivilEndpoint.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilDocumentResponseMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/DocumentMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/IssueMapper.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilApprMethodTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilDocumentTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilPartyTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilTest.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/TestHelpers.java
- implemented for getAppearanceCivilDocument
=> implemented for getAppearanceCivilDocument

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
Swagger yaml update for new ORDS GET endpoint civil/sync-civil-hrst/
=> GET sync-civil-hrst

src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilService.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilServiceImpl.java, src/libs/ords-pcss-client/src/main/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/mappers/SearchFileAppearanceResourcesResponseMapper.java, src/libs/ords-pcss-client/src/test/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilServiceGetAppearanceCivilResourceTest.java, src/libs/ords-pcss-client/src/test/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/CivilServiceGetCivilSearchFileAppearanceDocumentTest.java, src/libs/ords-pcss-client/src/test/java/ca/bc/gov/open/pcss/ords/pcss/client/civil/TestHelpers.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/PcssCivilEndpoint.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/AppearanceCivilResourceResponseMapper.java, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/civil/mappers/ResourceMapper.java, src/pcss-web-service/src/test/java/ca/bc/gov/open/pcss/pcsswebservice/civil/EndpointGetAppearanceCivilResource.java
- implementing getCivilResource
=> implementing getCivilResource

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
Swagger yaml update for new ORDS GET endpoint at /civil/file-content/counsel
=> get-civil-file-content-counsel

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
Jira Ticket PIM-26 - swagger update for the set civil appearance ORDS endpoint
=> set civil appearance

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
set civil appearance document swagger update for ORDS call
=> set civil appearance document

src/libs/ords-pcss-client/ords.pcss.swagger.yaml
PIM-28 - ORDS POST endpoint for setting civil appearance party data
- swagger update only!
=> Set Civil Appearance Party

.gitignore, src/pcss-web-service/Dockerfile, src/pcss-web-service/README.md, src/pcss-web-service/pom.xml, src/pcss-web-service/src/main/java/ca/bc/gov/open/pcss/pcsswebservice/PCSSWebServiceApplication.java
Switch project to build as WAR file for running on a JBoss-EAP-7.3 server
Added dockerfile to create image
Locally only.
=> JBoss Configure

.github/workflows/main.yml, .github/workflows/openshift-imagetagging.yml
- Updates made to handle both Gold Prod & DR clusters
Can be tested during dev oc deployment
=> Updates made to handle both Gold Prod & DR clusters

.github/workflows/main.yml, .github/workflows/openshift-imagetagging.yml, gitops/openshift/apps/jag-pcss-civil/template/jag-pcss-civil.yaml, gitops/openshift/apps/nginx/template/README.md, gitops/openshift/apps/nginx/template/nginx_jag_pcss.env, gitops/openshift/apps/nginx/template/nginx_jag_pcss.yaml, gitops/openshift/apps/nginx/template/nginx_jag_pcss_civil.env, gitops/openshift/apps/nginx/template/nginx_jag_pcss_civil_oldwm.env, gitops/openshift/apps/nginx/template/nginx_jag_pcss_oldwm.env, gitops/openshift/apps/nginx/template/nginx_jag_pcss_oldwm.yaml
- Updates made to accommodate oc silver deployment
Can be tested during silver deployment
=> Updates made to accommodate oc silver deployment

pcss-civil-application/src/main/java/ca/bc/gov/open/Pcss/Controllers/AppearanceController.java, pcss-civil-application/src/main/java/ca/bc/gov/open/Pcss/Controllers/SecureEndpointController.java, pcss-civil-application/src/main/java/ca/bc/gov/open/Pcss/Controllers/SyncController.java, pcss-civil-application/src/test/java/ca/bc/gov/open/Pcss/AppearanceControllerTests.java, pcss-civil-application/src/test/java/ca/bc/gov/open/Pcss/OrdsErrorTests.java, pcss-civil-application/src/test/java/ca/bc/gov/open/Pcss/SecureEndpointTests.java, pcss-civil-application/src/test/java/ca/bc/gov/open/Pcss/SyncControllerTests.java, pcss-models/src/main/resources/xsdSchemas/pcss-2.xsd, pcss-secure-models/src/main/resources/xsdSchemas/pcss-secure-3.xsd
=> fix date parsiing issues

AutomatedTests/cypress/integration/appearance_controller.spec.js, AutomatedTests/cypress/integration/health_controller.spec.js, AutomatedTests/cypress/integration/secure_endpoint_controller.spec.js, AutomatedTests/cypress/integration/sync_controller.spec.js, pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java, pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSCivilSecure.wsdl, pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl, pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java
=> Changed ws to civil

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSCivilSecure.wsdl, pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl
=> Reverted wsdl changes

pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java, pcss-civil-application/src/main/resources/application.yml, pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/AppearanceControllerTests.java, pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java, pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/SyncControllerTests.java, pcss-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantDeserializer.java, pcss-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSerializer.java, pcss-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSoapConverter.java, pcss-models/src/main/resources/jaxbConfigs/jaxb-datetime-binding.xjb, pcss-models/src/main/resources/xsdSchemas/pcss-civil-models-2.xsd
=> Timeformat fix

pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/controllers/SecureEndpointController.java, pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/exceptions/BadDateException.java, pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/SecureEndpointTests.java, pcss-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSerializer.java
- Time format and building uri correction
=> Time format and building uri correction

pcss-civil-application/src/test/java/ca/bc/gov/open/pcss/SecureEndpointTests.java, pcss-secure-models/src/main/resources/xsdSchemas/pcss-secure-models-3.xsd
=> DateType fix

pcss-civil-application/pom.xml, pcss-models/pom.xml, pcss-secure-models/pom.xml, pom.xml
- springframwork-core upgrade to 5.3.14
=> Springframwork core update

README.md, gitops/openshift/apps/jag-pcss-civil/template/jag-pcss-civil.yaml, pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java, pcss-civil-application/src/main/resources/application-test.yml, pcss-civil-application/src/main/resources/application.yml
=> add username and password to ORDS

pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java
=> use RestTemplateBuilder to create RestTemplate bean now

AutomatedTest/Dockerfile, AutomatedTest/pom.xml, pom.xml
=> XStream tomcat-embed-core spring-security-core spring-security-web

README.md, gitops/openshift/apps/jag-pcss-civil/template/jag-pcss-civil.yaml, pcss-civil-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java, pcss-civil-application/src/main/resources/application.yml
=> add 2 mins to ORDS read timeout to fix SocketTimeoutException: timeout

pcss-civil-application/src/main/resources/application-test.yml
=> fix unittest failure

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl, pcss-models/src/main/resources/xsdSchemas/pcss-civil-models-2.xsd
- [X ] My code follows the style guidelines of this project
=> Civil Appearance Fix

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSCivilSecure.wsdl, pcss-secure-models/src/main/resources/xsdSchemas/pcss-secure-models-3.xsd
=> add an opetion to CivilAppearance response

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl
=> remove getPing from wsdl to make a valid wsdl

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl
=> solve the 13 errors on loading the wsdl in eclipse

pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSCivilSecure.wsdl, pcss-civil-application/src/main/resources/xsdSchemas/JusticePCSSWSDL.wsdl, pcss-models/src/main/resources/xsdSchemas/pcss-civil-models-1.xsd, pcss-secure-models/src/main/resources/xsdSchemas/pcss-secure-models-1.xsd
=> change indigenousLawFileYn to IndigenousLawFileYn

AutomatedTest/pom.xml, pcss-civil-application/pom.xml, pom.xml
=> fix vulnerabilities

.github/workflows/codeclimate.yml, .github/workflows/main.yml
=> Updated upload-artifact to v4
